### ISSUE TITLE
Completar Checklist de Community Standards

### ISSUE THREAD

**Issue by Bruno-Felix** [DS-AmareloGirassol/AmareloGirassol-Docs#2]
### Descrição
Visualizar todos os requisitos de trabalho open source.

### Tarefas
- [x] Modificar nome do repositório após termos nosso tema;
- [x] Inserir descrição;
- [x] Inserir README;
- [x] Inserir código de conduta;
- [x] Inserir Issue e Pull request templates.

### Critérios de Aceitação:
- Todos os documentos tem que estar na língua portuguesa.
- Todos os membros concordarem com os documentos criados e mudanças feitas;

**Comment by Bruno-Felix** [comment]
Issue e Pull Request templates precisam seguir um padrão para o github identificalos como templates de fato.

Esses arquivos ficar na pasta .**github**

Exemplos:
Issue template: 
[ISSUE_TEMPLATE](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/tree/main/.github/ISSUE_TEMPLATE)
[ISSUE_TEMPLATE](https://github.com/fga-eps-mds/2020.1-VC_Usuario/tree/master/.github/ISSUE_TEMPLATE)

pr template:
[pull_request_template.md](https://github.com/fga-eps-mds/2020.1-VC_Usuario/blob/master/.github/pull_request_template.md)
[pull_request_template.md](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/blob/main/.github/pull_request_template.md)
